### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Maxi2022gt** [OldJERN8322/JERN_OS#5]
How do i enable the sound of intro on spanish version?

**Comment by Maxi2022gt** [comment]
ok, also, are you the real jern

**Comment by OldJERN8322** [comment]
Hmm. yea old account i like

**Comment by Maxi2022gt** [comment]
cool

**Comment by OldJERN8322** [comment]
Now. i have a new account

**Comment by OldJERN8322** [comment]
also data ago 2022/02/02: Old account its hacking and disable..

**Comment by Maxi2022gt** [comment]
Yea...

**Comment by OldJERN8322** [comment]
But Old account disable in: Discord, Roblox, Google account, Ect.

**Comment by Maxi2022gt** [comment]
Yes, rip.

**Comment by Maxi2022gt** [comment]
also i love your videos

**Comment by OldJERN8322** [comment]
Thanks! :D

**Comment by Maxi2022gt** [comment]
**:)**

**Comment by OldJERN8322** [comment]
Whoah!

**Comment by Maxi2022gt** [comment]
thats cool
should i change my pfp to my yt pfp?

**Comment by OldJERN8322** [comment]
Yes

**Comment by Maxi2022gt** [comment]
ok wait

**Comment by Maxi2022gt** [comment]
done

**Comment by OldJERN8322** [comment]
Okay nice

**Comment by Maxi2022gt** [comment]
:)

**Comment by OldJERN8322** [comment]
(:

**Comment by Maxi2022gt** [comment]
also when i see my pfp in the message part it shows my old pfp
![image](https://user-images.githubusercontent.com/106933671/184005109-a98a3502-0b03-4449-a4d4-436e7ff60989.png)

**Comment by OldJERN8322** [comment]
o also. hmm this a red line text

**Comment by Maxi2022gt** [comment]
yes bruh

**Comment by OldJERN8322** [comment]
Hmm. also i got disable autocorrect?

**Comment by Maxi2022gt** [comment]
idk

**Comment by OldJERN8322** [comment]
h

**Comment by Maxi2022gt** [comment]
h

**Comment by OldJERN8322** [comment]
Also. do you have a discord?

**Comment by Maxi2022gt** [comment]
i have one but only for messaging my friends
sorry

**Comment by OldJERN8322** [comment]
rip

**Comment by Maxi2022gt** [comment]
yeah rip

**Comment by Maxi2022gt** [comment]
im making a chat in my resposterys

**Comment by OldJERN8322** [comment]
ok

**Comment by Maxi2022gt** [comment]
its called "anychatinissuesordiscussions"
link is [https://github.com/Maxi2022gt/anychatinissuesordiscussions](url)

**Comment by OldJERN8322** [comment]
okay

**Comment by Maxi2022gt** [comment]
oops it searches the link

**Comment by OldJERN8322** [comment]
h

**Comment by Maxi2022gt** [comment]
also accept the collaborator request

**Comment by OldJERN8322** [comment]
rip dead chat lol

**Comment by Maxi2022gt** [comment]
I REMEMBER OGKNJDHIGUFDJSSDIJFXJSGFGFIGUJCUJFDUJDGIJORSFIJOTD
